REUSE Software Integration
clearlydefined/crawler pull request #452
Opened 2021-12-10 17:46 UTC by SebastianWolf-SAP

This PR integrates the [FSFE REUSE Software](https://reuse.software/) into the ClearlyDefined crawler. It is able to provide licensing and copyright attribution information especially for those projects that support the [REUSE specification](https://reuse.software/spec/) completely. For more details and backgrounds, please see https://github.com/clearlydefined/service/issues/883

In contrast to what I wrote in https://github.com/clearlydefined/service/issues/883, this change lets ClearlyDefined support REUSE natively, i.e. no external service calls are needed and the tool is executed for the same code that is analyzed by the other tools as well (not only the latest commit as expected originally).

2022-01-19 21:40 UTC, nellshamrell requested changes
A few comments and questions. Again, overall this looks good, and I really appreciate you adding in the thorough tests!

2022-01-19 21:40 UTC, nellshamrell commented on DevDockerfile
> +FROM node:16
I agree we should update to node 16 (and it's required for this change). I might introduce the Node upgrade in a separate pull request, though, to isolate it.

2022-01-19 21:40 UTC, nellshamrell commented on DevDockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev cmake python3 python3-pip && \
Adding python3 here will help us with some upgrades to scancode as well. Ty!

2022-01-19 21:40 UTC, nellshamrell commented on providers/process/fsfeReuse.js
> +      stdout.trim().split(/\n\n/).forEach((spdxResult, entryIndex) => {
This section is thorough, but I'm wondering if we can refactor it out into a few separate functions to make it a little more readable and maintainable.

2022-01-19 21:40 UTC, nellshamrell commented on providers/process/pypiExtract.js
> +    this.linkAndQueueTool(request, 'reuse')
Is there a reason to only have reuse queued up for pypi extractions? I believe we should add it for each of the other language/provider extractors as well.

2022-01-20 15:14 UTC, SebastianWolf-SAP commented on DevDockerfile
> +FROM node:16
OK, I can easily rebase later. Originally, I tried to stick to Node 14, but this one also include a too ancient version of Python. :(

2022-01-20 15:15 UTC, SebastianWolf-SAP commented on providers/process/fsfeReuse.js
> +      stdout.trim().split(/\n\n/).forEach((spdxResult, entryIndex) => {
Will do so, thanks for the hint. Sometimes, I tend to act like "it was hard enough to code, it should be as hard enough to read" - but of course, I shouldn't so that. :D

2022-01-20 15:17 UTC, SebastianWolf-SAP commented on providers/process/pypiExtract.js
> +    this.linkAndQueueTool(request, 'reuse')
Simply because I haven't tested other languages/providers. I was wondering if you have a certain real-life examples that I could run locally to feel a little bit safer...?

2022-01-20 23:56 UTC, nellshamrell commented on DevDockerfile
> +FROM node:16
Oh it's fine to keep it! I just might add in a separate Node 16 upgrade and merge it before I merge this one :)

2022-01-20 23:57 UTC, nellshamrell commented on providers/process/pypiExtract.js
> +    this.linkAndQueueTool(request, 'reuse')
I'll put some together for you :)

2022-01-25 00:14 UTC, nellshamrell commented on providers/process/pypiExtract.js
> +    this.linkAndQueueTool(request, 'reuse')
Here's a list of working coordinates for testing the various languages/providers:

- [ ] github component: git/github/bmitch/churn-php/473562efa0210a4cf3b1a7d66fd66be983d132cd
- [ ] gitlab component: git/gitlab/my-cloned-stuff/drgn/cf371594f3126c0fdd887bbd9d870eab7aa4739a
- [ ] maven central component: maven/mavencentral/io.nextflow/nextflow/21.10.4
- [ ] maven google component: maven/mavengoogle/android.arch.lifecycle/viewmodel/1.1.0
- [ ] crate component: crate/cratesio/-/rustversion/1.0.6
- [ ] npm component: npm/npmjs/-/pirates/4.0.4
- [ ] nuget component: nuget/nuget/-/Verify.NUnit/14.8.0
- [ ] composer component: composer/packagist/php-coveralls/php-coveralls/2.5.2
- [ ] gem component: gem/rubygems/-/effective_resources/1.9.8
- [ ] deb component: deb/debian/-/libserd-0-0/0.30.10-2_amd64
- [ ] deb source component: debsrc/debian/-/openexr/2.5.4-2

2022-01-26 19:16 UTC, nellshamrell commented on DevDockerfile
> +FROM node:16
I've upgraded our main branch to Node 16 and deployed it to production :)

2022-02-08 10:43 UTC, SebastianWolf-SAP commented on DevDockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev cmake python3 python3-pip && \
Seems that you integrated that already in upstream. :)

2022-02-15 20:02 UTC, nellshamrell commented
We did upgrade ScanCode recently and it is taking up more resources than before, unfortunately. I don't currently have any tips for improving the time, but will update here if I come up with some :)

Additionally, I am transitioning off of ClearlyDefined (I will be moving to another project in Microsoft), so @jeffwilcox and @fossygirl will be your contacts moving forward. It has been lovely to work with you and I hope we continue to have opportunities to collaborate!

2022-02-16 10:51 UTC, SebastianWolf-SAP commented
First, congratulations to you for your new role. Wish you all the best and of course fully agree with you: It has been a pleasure to work with you! Shall we reassign the PR reviewers already?

On the other side, I have to admit that the Scancode update virtually made testing impossible on my installation here. But well, maybe something else is wrong with the installation... Curious about your testing results of my changes.

2022-02-17 00:04 UTC, nellshamrell commented
@qtomlinson I think I remember you mentioned noticing that ScanCode is taking much more resources in your development environment. Do you have any tips for @SebastianWolf-SAP?

2022-02-17 00:43 UTC, qtomlinson commented
I am using dockerd on wsl/ubuntu.  No other special configs. Harvests are successful for most of the test cases.  Two cases where scancode results not saved are documented in https://github.com/clearlydefined/service/issues/846

2022-02-17 08:39 UTC, SebastianWolf-SAP commented
@qtomlinson Thanks for the reference! However, the actual results are not the problem. For the test cases I used locally, harvests are also OK in the end - they just take a lot more time compared to the situation before the upgrade. Harvests that were done in 1-2 minutes before, take more than half an hour now. Hope I find some time on Friday to test more. Btw, I'm using Docker Desktop/WSL2.

2022-02-17 22:42 UTC, nellshamrell commented
@SebastianWolf-SAP They definitely don't take that long for me with my Docker/WSL2 setup. I wonder if there's any way to allocate more resources to your Docker containers?

2022-02-18 08:59 UTC, SebastianWolf-SAP commented
OK, then I'll probably wipe everything and set it up again from scratch. Obviously, something must be wrong on my machine...

2022-03-23 15:19 UTC, SebastianWolf-SAP commented
@nellshamrell Are there any updates regarding new maintainers/reviewers for this PR and https://github.com/clearlydefined/service/pull/899? Happy to work together with the new folks to get this functionality finally merged (in case the CD community is still interested, of course ;)).

2022-03-23 17:30 UTC, nellshamrell commented
Tagging @jeffwilcox and @MichaelTsengLZ about @SebastianWolf-SAP's question above

2022-04-12 19:02 UTC, mpcen commented on test/unit/providers/process/composerExtractTests.js
> +      'reuse' /*, 'fossology'*/
nit: scancode -> fossology

2022-04-13 00:11 UTC, disulliv reviewed
Logic and code looks good to me, I want to test this locally with the other examples that Nell had, before approving.

2022-04-14 21:42 UTC, disulliv reviewed
I ran through all of Nell's suggested test cases, and they all looked good to me. @SebastianWolf-SAP Were there any other changes that you wanted to make before I approve and merge this? I think Manny had a nit if that was something you wanted to address before merging.

2022-04-19 14:15 UTC, SebastianWolf-SAP commented on test/unit/providers/process/composerExtractTests.js
> +      'reuse' /*, 'fossology'*/
I don't get this comment. What's the exact issue (maybe I need another coffee ;))?

2022-04-19 14:16 UTC, SebastianWolf-SAP commented
Thanks for the tests and the review! I'll provide the fixes to https://github.com/clearlydefined/service/pull/899 (and the one above if I understand the issue ;)) and then we can merge it. I'll let you know once I completed the changes.

2022-04-19 18:49 UTC, disulliv commented on test/unit/providers/process/composerExtractTests.js
> +      'reuse' /*, 'fossology'*/
Is it about the ordering of `licensee, scancode, fossology, reuse` instead of `licensee, scancode, reuse, fossology`?

```
'licensee',
'scancode' /*, 'fossology'*/
'reuse'
```

2022-04-20 08:28 UTC, SebastianWolf-SAP commented on test/unit/providers/process/composerExtractTests.js
> +      'reuse' /*, 'fossology'*/
Well, `fossology` is commented out anyway, but I'm fine with changing the position of the comment in case the comment should be enabled in the future again.

2022-04-20 08:34 UTC, SebastianWolf-SAP commented on test/unit/providers/process/composerExtractTests.js
> +      'reuse' /*, 'fossology'*/
Changed with https://github.com/clearlydefined/crawler/pull/452/commits/c8efb9b4f61c6c77d3e6e71b332d4d95e9895ea4

2022-04-20 12:09 UTC, SebastianWolf-SAP commented
@disulliv @mpcen Thanks again for your review. I changed the coding according to your proposals, please have a look and let me know in case further adjustments are needed. Feel free to merge the code from this PR and from https://github.com/clearlydefined/service/pull/899 at any time if you think it fits. :)

2022-04-26 23:30 UTC, merged

2022-04-27 00:03 UTC, disulliv commented
Changes have been merged into the [dev environment](https://dev.clearlydefined.io/). Please do some testing at your leisure then whenever you feel comfortable, I'll merge into production.

I've queued up [one of the examples ](https://dev.clearlydefined.io/definitions/git/github/corona-warn-app/cwa-server/34dd089e078bfedacfd6d61132dacfd928b05f75) from the issue to compare to the [existing definition in production](https://clearlydefined.io/definitions/git/github/corona-warn-app/cwa-server/34dd089e078bfedacfd6d61132dacfd928b05f75).

2022-04-27 17:50 UTC, qtomlinson commented
During merging this change into my PR, I noticed that reuse processor is not linked and queued in GoExtract.  Is this intentional?

2022-04-27 23:14 UTC, disulliv commented
I totally missed that, I don't think it's intentional though. @SebastianWolf-SAP could you add ReUse to the GoExtract as well, or let us know if there's any reason why not?

2022-04-28 07:03 UTC, SebastianWolf-SAP commented
@disulliv @qtomlinson It wasn't really intentional to ignore Go here - it's just that I went through the working examples provided in https://github.com/clearlydefined/crawler/pull/452#discussion_r791254232 and added reuse to the respective categories after I could test them successfully. Go wasn't among the examples, so I missed that. 😞 Providing the PR wouldn't be a big deal, but I won't have time to test things locally here over the next days and creating a PR without prior testing would actually be against my working style. 😉 So if someone of you wants to do that earlier, feel free to do so.

The same is true for testing the merged PR (thanks for that!) on dev - I have some urgent things to do here before I can come back to the topic again.

2022-04-28 18:21 UTC, qtomlinson commented
@disulliv @SebastianWolf-SAP I can help with this.  PodExtract likely needs to be adapted as well.

2022-04-29 15:02 UTC, qtomlinson commented
See https://github.com/clearlydefined/crawler/pull/472 for go and pod integration.  The coordinates tested:
- go/golang/rsc.io/quote/v1.3.0
- pod/cocoapods/-/SoftButton/0.1.0
The reuse result structure looks similar to that of a npm component.