conda crawler implementation
clearlydefined/crawler pull request #532
Opened 2023-11-15 14:51 UTC by lamarrr

This Merge request is intended to track the work in implementing the crawler for conda source packages.

## Background

Conda exposes packages in a different format from other python repositories like pypi. Conda is a python environment locked to a specific python version.
Conda deals with packages locked to a specific version for a version of the channel, this ensures packages do not break due to one incompatibility or another as the packages are managed for compatibility, similar to how you'd ship a docker container.
The primary consumption point is the "packages" themselves which are accompanied with scripts to modify the environment and setup the packages and dependencies which are then consumed by the setup application, the packages may also contain DLLs, scripts, compiled python binary (.pyc), python code. etc.
The structure of conda repositories are described here: https://docs.conda.io/projects/conda-build/en/stable/concepts/generating-index.html

We crawl both the packages and the source code (not always specified) for the licensing metadata and other metadata about the package.

2024-01-04 16:46 UTC, qtomlinson commented
It is exciting to see that a new harvester is being implemented!  This pull request provides a solid foundation for future enhancements.  A discussion is needed on the proposed coordinates, e.g. conda/conda-forge/-/numpy/1.13.0_linux-aarch64/py36. In the above proposal, toolVersion is used to represent the build (string) in conda-forge.  Points to consider:
- toolVersion is already used internally by ClearlyDefined as the harvest tool versioning, e.g.  Using spec.toolVersion will cause conflicts.  
- Adding /py36 adds complexity to [service APIs](https://api.clearlydefined.io/api-docs/#/).  For instance, harvest data api expects
/harvest/{type}/{provider}/{namespace}/{name}/{revision}/{tool}.
- Concatenating version and architecture with `_` does not handle versions that contain `_`, e.g. "version": "1.30.0_2018_09_30"

One possible alternative is to mirror the [package search standard specification](https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-search.html#standard-specification) in the CD's coordinates.  
![image](https://github.com/clearlydefined/crawler/assets/92891533/76fb1a72-355f-40d7-ab8a-fe2cce28c319)

The mapping would be as follows: 
```
channel -> provider
subdir -> namespace
name -> name
`${version}-${build}` -> revision 
```
Both version and build may not contain "-" (see https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#info-index-json). So using "-" as separator works here.

Additionally, when architecture platform is not specified, should 'noarch' be considered as the default value (https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/use-noarch-pkgs/)? This likely produces more predictive results.

@elrayle @capfei @jeffwilcox @pombredanne @bduranc I am not particularly knowledgeable in the conda ecosystem, and would very much appreciate other experts' input.

2024-01-04 18:56 UTC, bduranc commented
I'm okay with both proposals. Qing's is in-line with Conda's own standards, which I assume are applicable to all three channels.

I also assume the _type_ coordinate in both proposals would still be "conda" or "condasource". Also, if there is a GH or GitLab source location present in the channel / package [metadata](https://docs.conda.io/projects/conda-build/en/stable/concepts/generating-index.html), is the intent to populate the same in the definition?

In the past, I believe we've tried our best to keep the coordinate format consistent with the others (for example, when we added Debian/debsrc support back a few years ago, I believe that took some influence from the Maven implementation). It would be best to follow that practice as much as we can here too.

2024-01-05 12:58 UTC, lamarrr commented
> toolVersion is already used internally by ClearlyDefined as the harvest tool versioning. Using spec.toolVersion will cause conflicts.

I had the impression toolVersion was referring to the tool the package was built with and not of the tooling scanning the licensing info. which I feel would have been less ambiguous if it was at the beginning of the package coordinate.

> Adding /py36 adds complexity to [service APIs](https://api.clearlydefined.io/api-docs/#/). For instance, harvest data api expects
/harvest/{type}/{provider}/{namespace}/{name}/{revision}/{tool}.

Agreed, I'll make it an optional parameter appended to the revision instead

> Concatenating version and architecture with _ does not handle versions that contain _, e.g. "version": "1.30.0_2018_09_30"
Agreed, but I couldn't find a better delimiter to use. I performed a regex search on some of the channels and none of them had that kind of versioning (with '_' in them). it's always semantic versioning (numbers and hyphens only with alpha/beta, https://semver.org/).

The new revision can be `{architecture}--{version}-{build}`.

since architecture can be linux-64.

I feel noarch isn't the right thing. noarch is for platform-agnostic packages which may or may not be present. i.e. 7zip isn't platform-agnostic but is architecture and os dependent so it is not on the noarch list which would lead to fetching it without specifying the architecture to fail.
We presently select randomly from any architecture the package is available on (just as is done on the debian fetcher) which I feel is a much more reliable method than using noarch by default. It might be better to make the subdir/architecture&os required than using noarch. 

asides, subdir isn't really a namespace, it's just an architecture and os folder grouping of the packages (i.e. linux x64 packages -> /linux-64, windows x64 packages -> /windows-64)

2024-01-05 13:11 UTC, lamarrr commented
> I also assume the _type_ coordinate in both proposals would still be "conda" or "condasource". Also, if there is a GH or GitLab source location present in the channel / package [metadata](https://docs.conda.io/projects/conda-build/en/stable/concepts/generating-index.html), is the intent also to populate the same in the definition?

I don't get you, what definition?
If it is a condasource type, it is sourced from whatever source url or source git url (git is **NOT** always the source) is provided at the package's channel index.
if it is a conda type (architecture-dependent) it is sourced from conda's server source url

2024-01-05 17:33 UTC, bduranc commented
> > I also assume the _type_ coordinate in both proposals would still be "conda" or "condasource". Also, if there is a GH or GitLab source location present in the channel / package [metadata](https://docs.conda.io/projects/conda-build/en/stable/concepts/generating-index.html), is the intent also to populate the same in the definition?
> 
> I don't get you, what definition? If it is a condasource type, it is sourced from whatever source url or source git url (git is **NOT** always the source) is provided at the package's channel index. if it is a conda type (architecture-dependent) it is sourced from conda's server source url

Basically, a "definition" == component in ClearlyDefined. 

Using Maven as an example:
https://clearlydefined.io/definitions/maven/mavencentral/com.googlecode.openbox/maventools/2.0.1

and it's corresponding "source" definition (Maven sourcearchive): https://clearlydefined.io/definitions/sourcearchive/mavencentral/com.googlecode.openbox/maventools/2.0.1

Or another example that has a GitHub repo maintained as it's source location field instead of the Maven sourcearchive: https://clearlydefined.io/definitions/maven/mavencentral/io.eliez/mavenJava/2.0.1

2024-01-08 12:29 UTC, lamarrr commented
I have now changed the delimiters and coordinate specification to:

```
{type: conda|condasource}/{provider: anaconda-main|anaconda-r|conda-forge}/-/{package name}/[{archictecture | _}:][{version | _}]-[{build version | _}]/[{tool version}]
```

```
conda/conda-forge/-/numpy/linux-aarch64:1.13.0-py36/ - complete coordinate
conda/conda-forge/-/numpy/-py36/ -- any version with build hash py36*
conda/conda-forge/-/numpy/1.13.0-py36/ -- version with build hash
conda/conda-forge/-/numpy/linux-aarch64:_-py36/ -- architecture and build hash
conda/conda-forge/-/numpy/linux-aarch64:1.13.0/ -- architecture and version
conda/conda-forge/-/numpy/ - any
conda/conda-forge/-/numpy/_:_-_ - any
```

2024-01-08 14:08 UTC, lamarrr commented
> I have now changed the delimiters and coordinate specification to:
> 
> ```
> {type: conda|condasource}/{provider: anaconda-main|anaconda-r|conda-forge}/-/{package name}/[{archictecture | _}:][{version | _}]-[{build version | _}]/[{tool version}]
> ```
> 
> ```
> conda/conda-forge/-/numpy/linux-aarch64:1.13.0-py36/ - complete coordinate
> conda/conda-forge/-/numpy/-py36/ -- any version with build hash py36*
> conda/conda-forge/-/numpy/1.13.0-py36/ -- version with build hash
> conda/conda-forge/-/numpy/linux-aarch64:_-py36/ -- architecture and build hash
> conda/conda-forge/-/numpy/linux-aarch64:1.13.0/ -- architecture and version
> conda/conda-forge/-/numpy/ - any
> conda/conda-forge/-/numpy/_:_-_ - any
> ```

Seems the file indexer encodes the coordinates into files directly from the coordinate spec, meaning paths separated with `:` might not work. I have changed the spec to this:


```
{type: conda|condasource}/{provider: anaconda-main|anaconda-r|conda-forge}/-/{package name}/[{archictecture | _}--][{version | _}]-[{build version | _}]/[{tool version}]
```

```
conda/conda-forge/-/numpy/linux-aarch64--1.13.0-py36/ - complete coordinate
conda/conda-forge/-/numpy/-py36/ -- any version with build hash py36*
conda/conda-forge/-/numpy/1.13.0-py36/ -- version with build hash
conda/conda-forge/-/numpy/linux-aarch64--_-py36/ -- architecture and build hash
conda/conda-forge/-/numpy/linux-aarch64--1.13.0/ -- architecture and version
conda/conda-forge/-/numpy/ - any
conda/conda-forge/-/numpy/_--_-_ - any
```

2024-01-18 05:09 UTC, qtomlinson reviewed
Thanks for making the changes as discussed!  
I have reservations on treating condasrc as binary packages in recent commits(see email discussion).  Suggestions on condaFetch, condaExtract, and top below.

2024-01-18 05:09 UTC, qtomlinson commented on providers/process/top.js
> +    await request.queueRequests(slicedCoordinates.map(coord => new Request('package', coord)))
Assuming condasrc is for source files, 
-the corresponding request for condasrc coordinates would be new Request('source', coord)
-potentially, we can just process the top binary packages from repo data.  Each binary harvest will auto trigger source harvest if present.

2024-01-18 09:01 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +  //      {type: conda|condasrc}/{provider: anaconda-main|anaconda-r|conda-forge}/{architecture|-}/{package name}/[{version | _}]-[{build version | _}]/[{tool version}]
that's just the full coordinate as seen in the clearlydefined spec. for the clearlydefined tool, not conda's tool/build hash. but yeah, i'll remove it

2024-01-18 09:05 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +
yes, it is

2024-01-18 09:07 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +      declaredLicenses: packageChannelData.license,
yes, that's the format the service expects it in

2024-01-18 09:09 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +
the linter didn't catch that

2024-01-18 09:10 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +      return request.markSkip('No architecture build in package channel data')
that's a mistake, should have been === 'conda'

2024-01-18 09:12 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +
it already does that (fetch the latest one if version is not provided for both conda and condasrc)

2024-01-18 09:29 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    let packageRepoEntries = []
ok

2024-01-19 03:15 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +      declaredLicenses: packageChannelData.license,
"releaseDate": "Fri, 11 Jun 2021 02:25:26 GMT" is in the harvested file.

2024-01-19 03:55 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +      return request.markSkip('No architecture build in package channel data')
Line 52 - 60 related with type === conda, can be moved to _downloadCondaPackage, making the handle function simpler to read.

2024-01-19 03:58 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +
hm... it fetches the one with highest build, not latest version.  See a.packageData.build < b.packageData.build in _matchPackage.

2024-01-19 09:45 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +
the latest version is contained in packageChannelData.version, and the latest build of the version is obtained by sorting the build id

2024-01-19 09:48 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    if (version && version !== '_' && packageChannelData.version !== version) {
'_'  for version is necessary as we need both version and build in the revision, i.e. '{version}-{build}'
which we can't replace version with '-', otherwise we'd have bogus like '--py36'  which would be difficult to parse compared to '_-py36'

2024-01-24 01:43 UTC, qtomlinson commented on providers/process/condaExtract.js
> +      let sourceCandidates = [
To be consistent with the majority of the xxExtract classes, pls refactor line 27 - 47 to _discoverSource function

2024-01-24 01:43 UTC, qtomlinson commented on providers/process/condaExtract.js
> +        sourceInfo.version = null
version is still needed here, the intent here is to discover the source files for the same version as the harvested binary package.  It is understood that package channel data may not have the same version.

2024-01-24 01:43 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +    if (!(packageChannelData.subdirs.find(x => x === architecture))) {
nit, packageChannelData.subdirs[architecture]

2024-01-24 01:43 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +    if (packageRepoEntries.length == 0) {
===

2024-01-24 01:43 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +    if (version && version !== '_' && packageChannelData.version !== version) {
can potentially use empty string when version is not provided here, e.g. `-py36` for `{version}-{build}`.  After splitting using delimiter `-`, empty string for version and py36 for build.  This avoids the introduction of `_` as none for version, which can be confusing as `-` is used as none in architecture.

2024-01-24 02:23 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +      declaredLicenses: packageChannelData.license,
https://github.com/clearlydefined/service/blob/4ae722e9eaad2bada374df687c0a5dad9e1efe18/lib/utils.js#L116 tries to parse a date to a utc zoned date time.  Line 117 parses the string using ISO format first.   Release dates by most fetches are ISO format.

2024-01-24 09:59 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    if (!(packageChannelData.subdirs.find(x => x === architecture))) {
it's not an hashmap, it's a list of strings

2024-01-24 10:13 UTC, lamarrr commented on providers/process/condaSrcExtract.js
> +  constructor(options) {
the constructor is necessary as it contains the logger, and the basehandler needs it for logging. otherwise the crawler won't even start up

2024-01-24 14:07 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +      declaredLicenses: packageChannelData.license,
ok, done

2024-01-24 21:40 UTC, qtomlinson approved these changes
Thanks for your contribution and incorporating the comments!

2024-01-24 21:40 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +    return packageRepoEntries
b.packageData.build.localeCompare(a.packageData.build) puts lower build string first.  Is that the intent?
hm... Using the version string comparison to pick the latest version will run into problems.  For example, in versions, `'2018.12'` < `'2023.09'` <  `'5.0.0'`, `'2023.09'` is the latest version.  The current logic as it stands will not pick `'2023.09'` .  Can be a good unit test case here for `_matchPackage`.
One possible solution is to sort on `packageData.timestamp`, with highest (latest) coming first.  
Another possibility is to set version = version || packageChannelData.version in handle() before branching into processing source and package download.  This way puts the handling of version fallback in one central spot irrespective whether source or package is being fetched.

2024-01-25 10:24 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    return packageRepoEntries
b.compare(a) picks the greatest string via lexicographical comparison, a.compare(a) picks the smallest.
those are different versioning schemes, it wouldn't make sense for a single project to use different versioning schemes for a single project. yeah, I'll use the timestamp instead.
setting version to packageChannelData if none is specified won't work as the version is not always present.

2024-01-25 10:46 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    return packageRepoEntries
timestamp is for when it was last modified

2024-01-25 11:11 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    return packageRepoEntries
I've changed it to a priority-based selection, first prefer the highest version, then prefer the highest timestamp, then prefer the highest build

2024-01-26 04:04 UTC, qtomlinson requested changes

2024-01-26 04:04 UTC, qtomlinson commented on providers/fetch/condaFetch.js
> +    return packageRepoEntries
yes. you are right about build string comparison.
For latest version, using simple version string comparison will run in issue: lexically '5.0.0' > '10.0.0'. Example versions, '2018.12', '2023.09' and '5.0.0' are from repodata.json for anaconda_main/linux-64/_anaconda_depends, which may be a good test case. The current logic picks _anaconda_depends-5.3.1-py37_1.tar.bz2, while the latest version is 2023.09.

2024-01-26 13:41 UTC, lamarrr commented on providers/fetch/condaFetch.js
> +    return packageRepoEntries
I've changed to using timestamps instead

2024-01-26 23:12 UTC, qtomlinson approved these changes

2024-01-29 17:21 UTC, capfei commented
I don't have much knowledge in the crawler and conda but was able to get it running locally. This looks good to me and fine with the naming convention.

2024-05-02 04:30 UTC, merged

2024-10-14 14:48 UTC, RazaAli99 commented
Hi